# -*- coding: utf-8 -*-
"""priority.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8h4K_qkjubABUNHzhSkPd64dPueOXph
"""

# features.py

def sort_tasks(task_list, sort_by="priority"):
    """【功能：排序】使用泡沫排序法"""
    display_list = list(task_list)  # 複製清單避免影響原始資料
    n = len(display_list)

    for i in range(n):
        for j in range(0, n - i - 1):
            if sort_by == "priority":
                # 依優先度排序（1排最前面）
                if display_list[j]["priority"] > display_list[j+1]["priority"]:
                    display_list[j], display_list[j+1] = display_list[j+1], display_list[j]
            elif sort_by == "time":
                # 依時間排序：把日期和時間接起來直接當字串比大小
                time_j = display_list[j]["date"] + " " + display_list[j]["time"]
                time_j1 = display_list[j+1]["date"] + " " + display_list[j+1]["time"]
                if time_j > time_j1:
                    display_list[j], display_list[j+1] = display_list[j+1], display_list[j]
    return display_list

def search_tasks(task_list, keyword):
    """【功能：關鍵字搜尋】"""
    result = []
    for t in task_list:
        # 只要標題裡面包含關鍵字就抓出來
        if keyword in t["title"]:
            result.append(t)
    return result